/* 受講者データの読込・集計・検索 */
(function(){
  'use strict';
  const state={rows:[],headers:[],charts:{},selectedName:''};
  const aliases={name:['key_name','氏名','名前','受講者名','name'],facility:['facility','施設','所属施設','医療機関'],job:['job','職種'],role:['role','役割'],target:['target','対象','対象者'],date:['day','開催日','受講日','date'],attend:['attend_2026','attend','受講','出席','attendance'],certificate:['修了証書交付','修了証交付','修了証','certificate','certificate_issued','scc','web']};
  const $=id=>document.getElementById(id);
  const clean=v=>String(v==null?'':v).trim();
  const esc=v=>clean(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function keyOf(obj,list){const keys=Object.keys(obj);for(const a of list){const k=keys.find(x=>clean(x).toLowerCase()===a.toLowerCase());if(k)return k}return ''}
  function val(row,list){const k=keyOf(row,list);return k?clean(row[k]):''}
  function isAttended(row){const attendance=val(row,aliases.attend);return attendance==='1'||attendance==='１'}
  function formatDateValue(value){const text=clean(value);if(!text)return '';let match=text.match(/^(\d{4})[年\/-](\d{1,2})[月\/-](\d{1,2})日?/);if(!match&&/^\d{8}$/.test(text))match=text.match(/^(\d{4})(\d{2})(\d{2})$/);return match?`${match[1]}年${Number(match[2])}月${Number(match[3])}日`:text}
  function isYes(v){const text=clean(v);if(!text)return false;return /^(1|true|yes|y|有|済|交付|発行|完了|○|〇|あり)$/i.test(text)||/交付|発行|修了/.test(text)||/^(?:\d{4}[年\/-]\d{1,2}[月\/-]\d{1,2}日?|\d{1,2}[年\/-]\d{1,2}[月\/-]\d{1,2}日?)(?:\s+\d{1,2}:\d{2}(?::\d{2})?)?$/.test(text)}
  function normalize(headers,values){return headers.reduce((o,h,i)=>{if(clean(h))o[clean(h)]=values[i]==null?'':values[i];return o},{});} 
  function setStatus(message,type){$('loadStatus').textContent=message;$('statusDot').className='status-dot '+(type||'')}
  function parseWorkbook(data,name){try{const wb=XLSX.read(data,{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});if(!matrix.length)throw new Error('データ行がありません');const headers=matrix[0].map(clean);const rows=matrix.slice(1).filter(r=>r.some(v=>clean(v))).map(r=>normalize(headers,r));state.headers=headers;state.rows=rows;state.selectedName='';populateFilters();render();setStatus(`${name||'ファイル'}を読み込みました（${rows.length}件）`,'ready')}catch(e){console.error(e);setStatus('読み込みに失敗しました。列見出しとファイル形式を確認してください。','error')}}
  function unique(list){return [...new Set(list.map(clean).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ja'))}
  function fillSelect(id,items){const el=$(id);el.innerHTML='<option value="">すべて</option>'+items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
  function populateFilters(){fillSelect('facilityFilter',unique(state.rows.map(r=>val(r,aliases.facility))));fillSelect('jobFilter',unique(state.rows.map(r=>val(r,aliases.job))));fillSelect('roleFilter',unique(state.rows.map(r=>val(r,aliases.role))));}
  function filteredRows(){const f=$('facilityFilter').value,j=$('jobFilter').value,r=$('roleFilter').value;return state.rows.filter(isAttended).filter(x=>(!f||val(x,aliases.facility)===f)&&(!j||val(x,aliases.job)===j)&&(!r||val(x,aliases.role)===r))}
  function countBy(rows,field){const m={};rows.forEach(r=>{const v=val(r,aliases[field])||'未入力';m[v]=(m[v]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,12)}
  function chart(id,items,color){if(state.charts[id])state.charts[id].destroy();const ctx=$(id).getContext('2d');const styles=getComputedStyle(document.documentElement);state.charts[id]=new Chart(ctx,{type:'bar',data:{labels:items.map(x=>x[0]),datasets:[{data:items.map(x=>x[1]),backgroundColor:color,borderRadius:4}]},options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,ticks:{precision:0,color:styles.getPropertyValue('--muted')} ,grid:{color:styles.getPropertyValue('--line')}},y:{ticks:{color:styles.getPropertyValue('--text')} ,grid:{display:false}}}}})}
  function render(){const rows=filteredRows();const names=unique(rows.map(r=>val(r,aliases.name)));const certs=rows.filter(r=>isYes(val(r,aliases.certificate))).length;$('kpiRecords').textContent=rows.length.toLocaleString();$('kpiPeople').textContent=names.length.toLocaleString();$('kpiFacilities').textContent=unique(rows.map(r=>val(r,aliases.facility))).length.toLocaleString();$('kpiCertificates').textContent=certs.toLocaleString();$('kpiCertificateRate').textContent=rows.length?`受講記録の${Math.round(certs/rows.length*100)}%`:'—';$('topRecords').textContent=rows.length.toLocaleString();$('topPeople').textContent=names.length.toLocaleString();chart('facilityChart',countBy(rows,'facility'),'#38b6ff');chart('jobChart',countBy(rows,'job'),'#5ce1ff');chart('roleChart',countBy(rows,'role'),'#35e0b2');renderPeople(rows)}
  function renderPeople(rows){const q=clean($('nameSearch').value).toLowerCase();const grouped={};rows.forEach(r=>{const n=val(r,aliases.name)||'氏名未入力';if(!grouped[n])grouped[n]=[];grouped[n].push(r)});const people=Object.entries(grouped).filter(([n,rs])=>[n,val(rs[0],aliases.facility),val(rs[0],aliases.job)].join(' ').toLowerCase().includes(q)).sort((a,b)=>a[0].localeCompare(b[0],'ja'));$('searchCount').textContent=`${people.length}名`;$('peopleResults').innerHTML=people.length?people.map(([n,rs])=>{const ok=rs.some(r=>isYes(val(r,aliases.certificate)));return `<button class="person-card ${state.selectedName===n?'selected':''}" data-person="${esc(n)}"><strong>${esc(n)}</strong><small>${esc(val(rs[0],aliases.facility)||'施設未入力')} ／ ${esc(val(rs[0],aliases.job)||'職種未入力')}</small><small>受講 ${rs.length}回</small><span class="badge ${ok?'yes':'no'}">修了証書：${ok?'交付あり':'交付記録なし'}</span></button>`}).join(''):'<div class="empty-state">一致する受講者がありません。</div>';document.querySelectorAll('[data-person]').forEach(b=>b.addEventListener('click',()=>showPerson(b.dataset.person,rows)))}
  function csvCell(value){return `"${clean(value).replace(/"/g,'""')}"`}
  function exportPersonCsv(name,rows){const history=rows.filter(r=>val(r,aliases.name)===name);if(!history.length)return;const columns=[['開催日',aliases.date],['対象',aliases.target],['施設',aliases.facility],['部署',['department']],['職種',aliases.job],['役割',aliases.role],['修了証書交付',aliases.certificate]];const lines=[columns.map(x=>csvCell(x[0])).join(',')];history.forEach(r=>lines.push(columns.map(x=>{let value=val(r,x[1]);if(x[0]==='開催日')value=formatDateValue(value);if(!value&&x[0]==='修了証書交付')value='交付記録なし';return csvCell(value)}).join(',')));const blob=new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${name}_受講歴.csv`;a.click();URL.revokeObjectURL(url)}
  function showPerson(name,rows){state.selectedName=name;const history=rows.filter(r=>val(r,aliases.name)===name);const issued=history.some(r=>isYes(val(r,aliases.certificate)));$('personDetail').hidden=false;$('personDetail').innerHTML=`<div class="detail-title-row"><h3>${esc(name)} の受講歴</h3><button class="btn small" id="exportPersonCsv" type="button">CSV出力</button></div><div class="detail-summary"><span>受講回数：<b>${history.length}</b>回</span><span>修了証書：<b class="${issued?'yes':''}">${issued?'交付あり':'交付記録なし'}</b></span></div><div class="table-scroll"><table class="history-table"><thead><tr><th>開催日</th><th>対象</th><th>施設</th><th>職種</th><th>役割</th><th>修了証書</th></tr></thead><tbody>${history.map(r=>`<tr><td>${esc(formatDateValue(val(r,aliases.date))||'—')}</td><td>${esc(val(r,aliases.target)||'—')}</td><td>${esc(val(r,aliases.facility)||'—')}</td><td>${esc(val(r,aliases.job)||'—')}</td><td>${esc(val(r,aliases.role)||'—')}</td><td>${isYes(val(r,aliases.certificate))?'交付あり':'—'}</td></tr>`).join('')}</tbody></table></div>`;$('exportPersonCsv').addEventListener('click',()=>exportPersonCsv(name,rows));renderPeople(rows);$('personDetail').scrollIntoView({behavior:'smooth',block:'nearest'})}
  function readFile(file){const reader=new FileReader();reader.onload=e=>parseWorkbook(e.target.result,file.name);reader.onerror=()=>setStatus('ファイルを読み込めませんでした。','error');reader.readAsArrayBuffer(file)}
  async function autoLoad(){try{const res=await fetch('00_database_attends.xlsx');if(!res.ok)throw new Error('not found');parseWorkbook(await res.arrayBuffer(),'00_database_attends.xlsx')}catch(e){setStatus('xlsxを選択してください。','')}}
  document.addEventListener('DOMContentLoaded',()=>{if(window.SharedTheme)$('themeButton').addEventListener('click',SharedTheme.toggleTheme);$('attendeeFile').addEventListener('change',e=>{if(e.target.files[0])readFile(e.target.files[0])});const drop=document.querySelector('.file-drop');['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('dragover')}));drop.addEventListener('drop',e=>{if(e.dataTransfer.files[0])readFile(e.dataTransfer.files[0])});['facilityFilter','jobFilter','roleFilter'].forEach(id=>$(id).addEventListener('change',render));$('clearFilters').addEventListener('click',()=>{['facilityFilter','jobFilter','roleFilter'].forEach(id=>$(id).value='');render()});$('nameSearch').addEventListener('input',()=>renderPeople(filteredRows()));document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll).scrollIntoView({behavior:'smooth'})));autoLoad()});
})();
